### PR TITLE
a bit of php code added and the api micro framework readme

### PR DESCRIPTION
**Pull request by ideaguy3d**
Hi Linda 🤝  This is where I'm thinking the PHP & SQL code can live... even if the actual code lives on a separate server than the current cb-connect source. We can figure out how to wire everything up easily, I have a ton of experience doing this.

> If you don't want the php & sql code to live in this repo I completely understand 👍 
> if you want the code to live in a different folder just let me know 😄 
//

### CODE REVIEW

**Comment by ideaguy3d** [comment]
Hi, I would like to continue this project. How can we proceed?

**Comment by lpatmo** [comment]
Hi Julius! Feel free to fork this repo and work on a divergent repo!
Unfortunately I don't have the bandwidth to continue this immediately,
though it would now be nice to update the React now that I have a better
understanding of how React state can be organized, lol. Am focusing on
GitHub.com/codeBuddies/frontend when I have time now.

**Comment by ideaguy3d** [comment]
Okay, I'll start building it immediately. A prototype will be done in a week or 2. Do you want me to take over the UI development? Or can someone focus on the UI while I build the server side matching algorithms and set up the databases? I'll host the MySQL DB in my personal cloud, we can always do a migration if you want the data and schema's to be on your servers. 

**Personally** I would like someone to help me with the UI development. Do you know anyone can that can help me with the UI ?

**Comment by lpatmo** [comment]
> Personally I would like someone to help me with the UI development. Do you know anyone can that can help me with the UI ?

The #personal-projects channel on the [CodeBuddies Slack](https://codebuddies.org/slack) might be a good place to ask. :) Would also be helpful to specify if you want the UI lead to focus on any particular front-end framework.

I've starred your repo -- look forward to following along! If we decide to use your fork for a beta, I'll set up a MySQL DB. Thanks!

**Comment by ideaguy3d** [comment]
Hi Linda, should I continue to development this API?

**Comment by lpatmo** [comment]
@ideaguy3d As I mentioned last week, feel free to run with the fork on a divergent repo/as your own project -- the repo is open-sourced under a GPLV3 license, after all.

**Comment by ideaguy3d** [comment]
K. I've migrated the entire source to Google Cloud app engine and CloudSQL (MySQL). I hit some very frustrating issues with my linux web hosting. At this point PHP is connecting to the db and doing client side request via prepared statements. Everything else should be downhill from here, making that initial connection was a pain in the neck. 

Pretty soon I'd like to have someone help with the UI. I can't go on slack anymore... 

Here is the temporary url:

- [basic landing](https://cb-connect-api.uc.r.appspot.com)
- [basic db query](https://cb-connect-api.uc.r.appspot.com/test1)

**Comment by ideaguy3d** [comment]
Hi, I'm curious about the status of this pull request? 

The prototype is 90% complete. The "Skills" match query broke once I deployed to Google Cloud which I'll get fixed in a day or 2. 

# [The Cloud App Prototype](https://cb-connect-api.appspot.com/test/get-matched)

Next steps are to combine the 2 result sets then render the matches using either

- https://material.angularjs.org/latest/demo/list
- https://material.angularjs.org/latest/demo/card

I'd like to figure out how to combine the prior work to the Cloud App I've built.

**Comment by ideaguy3d** [comment]
Hi, just wanted to reach out 1 last time before I close this pull request, clone the repo, start a new github organization, and but a completely separate domain name to point to this cloud app. I was really hoping to join code buddies, but it's been 10 days and I haven't got a response.

**Pull request closed without merging**
